# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ebe06dfd29d1a471cf52210f18501ec7"
name = "Cart Auto Gift"
handle = "cart-auto-gift"
application_url = "https://usual-washing-invited-anger.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "yanyi-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,read_shipping,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://usual-washing-invited-anger.trycloudflare.com/auth/callback",
  "https://usual-washing-invited-anger.trycloudflare.com/auth/shopify/callback",
  "https://usual-washing-invited-anger.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
